/**
 * AWIE V2 - Phase 16.5: Plugin SDK - Test Harness.
 *
 * ============================================================================
 * ADR-010 (Developer Experience & SDK Strategy) — API NAMING FREEZE
 * ============================================================================
 * The Architecture Review Board has FROZEN the following public API names for
 * the Plugin Test Harness:
 *
 *   - createThemeFixture()  (NOT "createMockTheme")
 *   - createRuntimeStub()   (NOT "createMockRuntime")
 *
 * These names are permanent public contracts. They MUST NOT be renamed.
 *
 * SCOPE (ADR-010): createRuntimeStub does NOT duplicate the real runtime. It
 * exposes ONLY a thin emitSnapshot(snapshot) -> HydrationInstruction[] pipeline
 * for testing UI state. It never resolves, edits, composes, validates, or
 * decides (ADR-008 Runtime Purity).
 *
 * The harness is framework-agnostic: it exposes plain functions that return
 * plain fixtures. Vitest/Jest provide the runner, assertions, and watch mode.
 *
 * STRICT CONSTRAINT: This module MUST NOT contain any business logic. It is a
 * pure contract for the Developer Platform.
 */

import type { ThemeConfig } from '../../theme-config/v2';
import type {
  HydrationInstruction,
  PermissionSnapshot,
  PermissionVerdict,
} from '../../../runtime/core/types';
import type { RuntimeStub, ThemeFixture } from './types';

// Re-export the public fixture types so consumers can import them directly
// from the @awie/sdk barrel (ADR-010 API Naming Freeze).
export type { PluginCapability, RuntimeStub, ThemeFixture } from './types';


/**
 * Builds a frozen, deterministic ThemeConfig fixture.
 *
 * The returned config is a minimal, valid ThemeConfig that satisfies the
 * @awie/sdk theme contract. It is immutable and safe for plugin tests.
 *
 * @returns A ThemeFixture wrapping the frozen ThemeConfig.
 */
export function createThemeFixture(): ThemeFixture {
  const config: ThemeConfig = {
    metadata: {
      title: 'AWIE Test Fixture',
      tagline: 'A deterministic ThemeConfig for plugin tests.',
      description: 'A minimal ThemeConfig fixture generated by createThemeFixture().',
      locale: 'ko',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
      generator: 'awie-sdk',
      generatorVersion: '2.0.0',
    },
    intent: 'brand_experience',
    resources: {
      pages: [
        {
          id: 'home',
          route: '/',
          title: 'Home',
          sectionIds: ['hero'],
          isHome: true,
        },
      ],
      sections: [
        {
          id: 'hero',
          type: 'hero',
          content: {
            headline: 'Welcome',
            subheadline: 'A test hero section.',
          },
        },
      ],
      assets: [],
      settings: {
        primaryColor: '#4f46e5',
        secondaryColor: '#0ea5e9',
        backgroundColor: '#ffffff',
        textColor: '#111827',
        font: 'sans',
        spacing: 'md',
        radius: 'md',
      },
      menus: [],
      forms: [],
    },
    seo: {
      canonical: 'https://example.com/',
      robots: 'index,follow',
      openGraph: {
        title: 'AWIE Test Fixture',
        type: 'website',
      },
    },
    policies: {},
  };

  // The fixture is frozen to guarantee immutability during tests.
  return { config: Object.freeze(config) };
}

/**
 * Translates a single PermissionVerdict into a rich HydrationInstruction.
 *
 * ============================================================================
 * ADR-009 (Permission Snapshot) — LEVEL B: VERDICT vs. INSTRUCTION SEPARATION
 * ============================================================================
 * This is a PURE dictionary join: targetId -> HydrationInstruction. It NEVER
 * evaluates authorization rules (Zero Engine Rule). The engine blindly trusts
 * the snapshot.
 *
 * @param verdict The raw permission verdict.
 * @returns The rich hydration instruction for the verdict.
 */
function verdictToInstruction(verdict: PermissionVerdict): HydrationInstruction {
  // A hidden target is fully hidden.
  if (verdict.visibility === 'hide') {
    return { targetId: verdict.targetId, permission: 'hide' };
  }

  // A visible but disabled target is masked (rendered but non-interactive).
  if (!verdict.enabled) {
    return { targetId: verdict.targetId, permission: 'mask' };
  }

  // A visible and enabled target is shown normally.
  return { targetId: verdict.targetId };
}

/**
 * Builds a thin RuntimeStub for testing plugin UI state.
 *
 * The stub exposes ONLY the emitSnapshot(snapshot) -> HydrationInstruction[]
 * pipeline. It does NOT duplicate the real runtime. It never resolves, edits,
 * composes, validates, or decides (ADR-008 Runtime Purity).
 *
 * @returns A RuntimeStub.
 */
export function createRuntimeStub(): RuntimeStub {
  return {
    emitSnapshot(snapshot: PermissionSnapshot): readonly HydrationInstruction[] {
      // A pure, deterministic translation of verdicts into instructions.
      // The stub blindly trusts the snapshot (ADR-009 Zero Engine Rule).
      return snapshot.verdicts.map(verdictToInstruction);
    },
  };
}
