/**
 * AWIE V2 - Phase 16.5: Plugin SDK - Test Harness Types.
 *
 * ============================================================================
 * ADR-010 (Developer Experience & SDK Strategy) — API NAMING FREEZE
 * ============================================================================
 * The Architecture Review Board has FROZEN the following public API names for
 * the Plugin Test Harness:
 *
 *   - createThemeFixture()  (NOT "createMockTheme")
 *   - createRuntimeStub()   (NOT "createMockRuntime")
 *
 * These names are permanent public contracts. They MUST NOT be renamed.
 *
 * SCOPE (ADR-010): createRuntimeStub does NOT duplicate the real runtime. It
 * exposes ONLY a thin emitSnapshot(snapshot) -> HydrationInstruction[] pipeline
 * for testing UI state. It never resolves, edits, composes, validates, or
 * decides (ADR-008 Runtime Purity).
 *
 * STRICT CONSTRAINT: This module MUST NOT contain any business logic. It is a
 * pure contract for the Developer Platform.
 */

import type { ThemeConfig } from '../../theme-config/v2';
import type {
  HydrationInstruction,
  PermissionSnapshot,
} from '../../../runtime/core/types';

/**
 * The capability of a generated plugin.
 *
 * ============================================================================
 * ADR-010 (API Naming Freeze) — CAPABILITY GENERATION
 * ============================================================================
 * The CLI generator focuses on CAPABILITY generation, not rigid domain
 * templates (e.g., "music" or "commerce"). A plugin is generated by its
 * capability:
 *
 *   - 'static'  - CMS Theme & Components only (no live adapters).
 *   - 'live'    - Requires TanStack Live Adapters (live data).
 *   - 'hybrid'  - Both static and live.
 *
 * This is a permanent public contract.
 */
export type PluginCapability = 'static' | 'live' | 'hybrid';

/**
 * The result of a createThemeFixture() call.
 *
 * A frozen, deterministic ThemeConfig fixture that satisfies the @awie/sdk
 * theme contract. It is immutable and safe for plugin tests.
 */
export interface ThemeFixture {
  /**
   * The frozen ThemeConfig fixture.
   */
  readonly config: ThemeConfig;
}

/**
 * The result of a createRuntimeStub() call.
 *
 * A thin stub that exposes ONLY the emitSnapshot pipeline for testing UI
 * state. It does NOT duplicate the real runtime.
 */
export interface RuntimeStub {
  /**
   * Emits a PermissionSnapshot and returns the resulting HydrationInstructions.
   *
   * This is a PURE pipeline: snapshot -> HydrationInstruction[]. It never
   * evaluates authorization rules (ADR-009 Zero Engine Rule). It is used to
   * test how a plugin's UI state responds to a given permission snapshot.
   *
   * @param snapshot The immutable PermissionSnapshot to emit.
   * @returns The hydration instructions for the given snapshot.
   */
  emitSnapshot(snapshot: PermissionSnapshot): readonly HydrationInstruction[];
}
