/**
 * AWIE V2 - Product Development Phase: Reference Products Verification.
 *
 * Proves the 6 Business Reference Websites are production-ready by rendering
 * each product's ThemeConfig (the SSOT) through the FROZEN Golden Path
 * orchestrator. This is the "One-Line UX" Proof: each product's single logical
 * AI input resolves into a complete ThemeConfig that deterministically renders
 * into a valid RenderNode tree.
 *
 * MANDATES VALIDATED:
 *   - MANDATE 1: Each product is a complete, valid ThemeConfig (the SSOT).
 *   - MANDATE 2: Each product renders through the frozen Golden Path with NO
 *     engine modification. The engine is a dependency, never a target.
 *   - MANDATE 3: DETERMINISM. The same product always produces the same
 *     RenderNode tree.
 *
 * Run with: npx tsx scripts/products-test.ts
 */

import * as React from 'react';
import {
  buildGoldenPathRegistries,
  DefaultGoldenPathOrchestrator,
} from '../src/lib/golden-path';
import { buildProductConfig } from '../products/shared/scaffold';
import { REFERENCE_PRODUCTS } from '../products';
import type { RenderNode } from '../src/lib/renderer-foundation';

// ---------------------------------------------------------------------------
// Test harness
// ---------------------------------------------------------------------------

let passed = 0;
let failed = 0;

function assert(condition: boolean, message: string): void {
  if (condition) {
    passed++;
    console.log(`  PASS: ${message}`);
  } else {
    failed++;
    console.error(`  FAIL: ${message}`);
  }
}

function section(name: string): void {
  console.log(`\n=== ${name} ===`);
}

// ---------------------------------------------------------------------------
// Build the frozen Golden Path once (shared across all products)
// ---------------------------------------------------------------------------

const registries = buildGoldenPathRegistries();
const orchestrator = new DefaultGoldenPathOrchestrator(registries);

// ---------------------------------------------------------------------------
// MANDATE 1 + 2: Each product resolves into a valid ThemeConfig and renders
// ---------------------------------------------------------------------------

section('MANDATE 1+2: All 6 Reference Products resolve and render');

assert(
  REFERENCE_PRODUCTS.length === 6,
  `the registry contains exactly 6 Reference Products (found ${REFERENCE_PRODUCTS.length})`,
);

for (const product of REFERENCE_PRODUCTS) {
  section(`Product: ${product.title} (${product.id})`);

  // Resolve the product brief into a complete ThemeConfig (the SSOT).
  const config = buildProductConfig(product.declaration);

  // The config carries the product identity.
  assert(
    config.metadata.title === product.title,
    'the ThemeConfig carries the product title',
  );
  assert(
    config.metadata.generator === 'awie-product-scaffold',
    'the ThemeConfig is generated by the product scaffold (not the engine)',
  );

  // The config has at least one page and one section.
  assert(
    config.resources.pages.length >= 1,
    `the config declares ${config.resources.pages.length} page(s)`,
  );
  assert(
    config.resources.sections.length >= 1,
    `the config declares ${config.resources.sections.length} section(s)`,
  );

  // Every page renders through the frozen Golden Path.
  for (const page of config.resources.pages) {
    const result = orchestrator.renderPage(config, page.id);

    // The result carries BOTH the framework-agnostic RenderNode AND the React
    // element tree. This proves the frozen pipeline rendered the product.
    assert(
      result.renderNode !== undefined && result.renderNode.type === 'fragment',
      `page "${page.id}" renders a framework-agnostic RenderNode tree`,
    );
    assert(
      result.reactElement !== undefined,
      `page "${page.id}" renders a materialized React element tree`,
    );

    // The RenderNode is a fragment wrapping the ordered section nodes.
    const fragment = result.renderNode as Extract<RenderNode, { type: 'fragment' }>;
    assert(
      fragment.children.length === page.sectionIds.length,
      `page "${page.id}" renders exactly ${page.sectionIds.length} sections in order`,
    );

    // Every section node is a valid element node.
    for (const child of fragment.children) {
      const element = child as Extract<RenderNode, { type: 'element' }>;
      assert(
        element.type === 'element' && element.componentId !== undefined,
        `section "${element.id}" resolves to a valid element node (${element.componentId})`,
      );
    }

  }

  // The config declares a main navigation menu.
  assert(
    config.resources.menus.length >= 1,
    'the config declares a navigation menu',
  );

  // The config declares at least one form (conversion focus).
  assert(
    config.resources.forms.length >= 1,
    'the config declares a conversion form',
  );

  // The config declares a flat asset registry.
  assert(
    config.resources.assets.length >= 1,
    `the config declares ${config.resources.assets.length} asset(s)`,
  );

  // The AI design report is present (the AI decided; the renderer renders).
  const report = config.resources.settings.aiDesignReport;
  assert(
    report !== undefined && report.analyzedIndustry === product.declaration.industry,
    `the AI design report identifies the industry as "${product.declaration.industry}"`,
  );
}

// ---------------------------------------------------------------------------
// MANDATE 3: DETERMINISM (same product -> same output)
// ---------------------------------------------------------------------------

section('MANDATE 3: Determinism (same product -> same output)');

for (const product of REFERENCE_PRODUCTS) {
  const config = buildProductConfig(product.declaration);
  const home = config.resources.pages.find((p) => p.isHome) ?? config.resources.pages[0];

  const resultA = orchestrator.renderPage(config, home.id);
  const resultB = orchestrator.renderPage(config, home.id);

  assert(
    JSON.stringify(resultA.renderNode) === JSON.stringify(resultB.renderNode),
    `${product.id}: the same ThemeConfig always produces the same RenderNode tree`,
  );
  assert(
    JSON.stringify(resultA.reactElement) === JSON.stringify(resultB.reactElement),
    `${product.id}: the same RenderNode always produces the same React element tree`,
  );
}

// ---------------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------------

console.log(`\n----------------------------------------`);
console.log(`Reference Products Test: ${passed} passed, ${failed} failed`);
console.log(`----------------------------------------`);

if (failed > 0) {
  process.exit(1);
}
