/**
 * AWIE V2 - Immutable BusinessBrief & Patch System.
 *
 * The BusinessBrief is the immutable Single Source of Truth for a site's
 * business context. It is NEVER mutated in place. All changes flow through a
 * BusinessBriefPatch, which the MergeEngine applies to produce a NEW brief
 * with an incremented version number.
 *
 * Core slots:
 *   businessType, goals, audience, personality, services, contactPreference,
 *   optionalPreferences.
 *
 * STRICT CONSTRAINT: This module MUST NOT contain any business logic. It is
 * pure data modeling + a deterministic merge utility.
 */

import { z } from 'zod';

/** The current schema version of the BusinessBrief. */
export const BRIEF_SCHEMA_VERSION = 1;

/** A confidence value between 0 and 1 (e.g. 0.95 = 95%). */
export type Confidence = number;

/** A stable identifier for a brief slot. */
export type SlotKey =
  | 'businessType'
  | 'goals'
  | 'audience'
  | 'personality'
  | 'services'
  | 'contactPreference'
  | 'optionalPreferences';

/** All slot keys, in canonical order. */
export const SLOT_KEYS: readonly SlotKey[] = [
  'businessType',
  'goals',
  'audience',
  'personality',
  'services',
  'contactPreference',
  'optionalPreferences',
];

/** Zod schema for the businessType slot. */
export const businessTypeSchema = z.object({
  /** The primary business type (e.g. "restaurant"). */
  primary: z.string().min(1),
  /** Optional secondary business types. */
  secondary: z.array(z.string()).default([]),
});

/** Zod schema for the goals slot. */
export const goalsSchema = z.object({
  /** The primary business goal (e.g. "increase_orders"). */
  primary: z.string().min(1),
  /** Additional goals. */
  additional: z.array(z.string()).default([]),
});

/** Zod schema for the audience slot. */
export const audienceSchema = z.object({
  /** The primary target audience. */
  primary: z.string().min(1),
  /** Secondary audience segments. */
  secondary: z.array(z.string()).default([]),
});

/** Zod schema for the personality slot. */
export const personalitySchema = z.object({
  /** The brand personality/tone (e.g. "friendly", "premium"). */
  tone: z.string().min(1),
  /** Optional brand values. */
  values: z.array(z.string()).default([]),
});

/** Zod schema for the services slot. */
export const servicesSchema = z.object({
  /** The list of services/products offered. */
  items: z.array(z.string()).default([]),
});

/** Zod schema for the contactPreference slot. */
export const contactPreferenceSchema = z.object({
  /** The preferred contact channel (e.g. "phone", "email"). */
  channel: z.string().min(1),
  /** The contact value (e.g. phone number or email address). */
  value: z.string().min(1),
});

/** Zod schema for the optionalPreferences slot. */
export const optionalPreferencesSchema = z.record(z.string(), z.unknown());


/**
 * The immutable BusinessBrief.
 *
 * All slots are optional at the type level because the brief is progressively
 * filled through the Question Engine. A slot is "filled" when its confidence
 * reaches a threshold.
 */
export interface BusinessBrief {
  /** The schema version. */
  schemaVersion: number;
  /** The brief version, incremented on every merge. */
  version: number;
  /** The business type slot. */
  businessType?: z.infer<typeof businessTypeSchema>;
  /** The goals slot. */
  goals?: z.infer<typeof goalsSchema>;
  /** The audience slot. */
  audience?: z.infer<typeof audienceSchema>;
  /** The personality slot. */
  personality?: z.infer<typeof personalitySchema>;
  /** The services slot. */
  services?: z.infer<typeof servicesSchema>;
  /** The contactPreference slot. */
  contactPreference?: z.infer<typeof contactPreferenceSchema>;
  /** The optionalPreferences slot. */
  optionalPreferences?: z.infer<typeof optionalPreferencesSchema>;
}

/**
 * A partial representation of the brief generated by the AI.
 *
 * The AI does NOT decide business types; it only EXTRACTS them into a patch.
 * A patch may also carry per-field confidence updates.
 */
export interface BusinessBriefPatch {
  /** The business type slot, if extracted. */
  businessType?: z.infer<typeof businessTypeSchema>;
  /** The goals slot, if extracted. */
  goals?: z.infer<typeof goalsSchema>;
  /** The audience slot, if extracted. */
  audience?: z.infer<typeof audienceSchema>;
  /** The personality slot, if extracted. */
  personality?: z.infer<typeof personalitySchema>;
  /** The services slot, if extracted. */
  services?: z.infer<typeof servicesSchema>;
  /** The contactPreference slot, if extracted. */
  contactPreference?: z.infer<typeof contactPreferenceSchema>;
  /** The optionalPreferences slot, if extracted. */
  optionalPreferences?: z.infer<typeof optionalPreferencesSchema>;
  /** Per-field confidence updates (0..1). */
  confidence?: Partial<Record<SlotKey, Confidence>>;
}

/** Creates an empty, immutable BusinessBrief. */
export function createEmptyBrief(): BusinessBrief {
  return {
    schemaVersion: BRIEF_SCHEMA_VERSION,
    version: 0,
  };
}

/**
 * The MergeEngine.
 *
 * Applies a BusinessBriefPatch to the current BusinessBrief and returns a NEW
 * brief with an incremented version number. The original brief is never
 * mutated.
 */
export class MergeEngine {
  /**
   * Applies a patch to a brief, returning a new brief.
   *
   * Only slots present in the patch are overwritten. The version is
   * incremented by 1 on every merge.
   */
  apply(current: BusinessBrief, patch: BusinessBriefPatch): BusinessBrief {
    const next: BusinessBrief = {
      ...current,
      version: current.version + 1,
    };

    // Apply each slot explicitly. Only slots present in the patch overwrite
    // the current value. This keeps the merge deterministic and type-safe.
    if (patch.businessType !== undefined) {
      next.businessType = patch.businessType;
    }
    if (patch.goals !== undefined) {
      next.goals = patch.goals;
    }
    if (patch.audience !== undefined) {
      next.audience = patch.audience;
    }
    if (patch.personality !== undefined) {
      next.personality = patch.personality;
    }
    if (patch.services !== undefined) {
      next.services = patch.services;
    }
    if (patch.contactPreference !== undefined) {
      next.contactPreference = patch.contactPreference;
    }
    if (patch.optionalPreferences !== undefined) {
      next.optionalPreferences = patch.optionalPreferences;
    }

    return next;
  }

}
